algo = input(('Digite algo: '))
print('O tipo primitivo desse valor é: ', type(algo))
print('Só tem espaços?', algo.isspace())
print('Só um número?', algo.isdigit())
print('É alfabético?', algo.isalpha())
print('É um alfanumérico?', algo.isalnum())
print('É maiúscula?', algo.isupper())
print('É minúsucla?', algo.islower())
print('É capitalizada?', algo.istitle())