times = ('Botafogo', 'RB Brangantino', 'Palmeiras', 'Flamengo', 'Atletico Paranaense', 'Gremio', 'Altetico-MG', 'Fluminense', 'Fortaleza EC', 'São Paulo')
print(f'Lista de times do Brasileirão: {times[:]}')
print('='*60)
print(f'Os 5 primeiros são: {times[:5]}')
print('='*60)
print(f'Os 4 últimos são {times[-4:]}')
print('='*60)
print(f'Times em ordem alfabética: {sorted(times)}')
print('='*60)
print(f'O Flamengo está na {times.index("Flamengo")+1}º posição')
print('='*60)
